import CourseCard from "@/components/cards/CourseCard";
import { courses } from "@/static/data";
import React from "react";

const MyCourses = () => {
  const [currentPage, setCurrentPage] = useState(1);
  const [totalPage, setTotalPage] = useState(1);
  
  return (
    <main>
      <div class="mx-auto bg-beta text-ta-black flex items-center">
        <div class="container max-w-7xl w-full grid grid-cols-6 items-center gap-5 py-16">
          <div class="col-span-6 sm:col-span-4 flex flex-col gap-5">
            <div class="font-medium text-3xl sm:text-4xl md:text-5xl">
              Your Courses
            </div>
            <p class="sm:text-lg">
              Explore some of our courses generated by other users to help you
              get started with Tutor AI.
            </p>
          </div>
        </div>
      </div>
      <section class="container max-w-7xl w-full grid sm:grid-cols-2 md:grid-cols-3 gap-4 py-10 sm:py-12">
        {courses?.map((course, i) => (
          <CourseCard data={course} />
        ))}
      </section>
    </main>
  );
};

export default MyCourses;
